---
galaxy_info:
  author: x
  description: x
  company: x
  min_ansible_version: 1.5
  version: 0.1
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - wheezy
  categories:
  - development
  - system
dependencies: []
