---
# tasks file for mailcatcher
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Add Brightbox signing keys
  apt_key: keyserver=keyserver.ubuntu.com id=80F70E11F0F0D5F10CB20E62F5DA5F09C3173AA6

- name: Add Brightbox ppa for ruby
  apt_repository: repo='ppa:brightbox/ruby-ng' update_cache=yes
  tags: [mailcatcher, packages]

- name: Install the mailcatcher prerequisites (APT)
  apt: name="{{ item }}" state=latest update_cache=yes
  with_items: "{{ mailcatcher_packages }}"
  when: ansible_os_family == "Debian"
  tags: [mailcatcher, packages]

- name: Make the ruby switch to 2.2
  command: ruby-switch --set ruby2.2
  tags: [mailcatcher, packages]

- name: Install the mailcatcher (GEM)
  # gem module is flaky, this is consistent
  command: gem install mailcatcher
  tags: [mailcatcher, packages]

- name: Setup the upstart script
  template: src=mailcatcher.j2
            dest="{{ upstart_init_path }}/mailcatcher.conf"
            backup=yes
            owner=root
            group=root
            mode=0644
  when: ansible_os_family == "Debian"
  notify:
   - restart mailcatcher
  tags: [mailcatcher, upstart]
