---
galaxy_info:
  author: Srdjan Vranac
  description: Setup composer and install vendors
  company: Code4Hire Kft.
  min_ansible_version: 1.5
  version: 0.1
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - wheezy
  categories:
  - development
  - system
dependencies: []

