---
# vars file for php

env:
 RUNLEVEL: 1

php_packages:
  - php5-dev
  - php5-cli
  - php5-mysql
  - php5-pgsql
  - php-pear
  - php5-mcrypt
  - php5-curl
  - php5-gd
  - php5-intl
  - php5-xsl
  - imagemagick
  - php5-imagick
  - php5-gd

php_xdebug:
  - php5-xdebug

php_nofpm_packages:
  - libapache2-mod-php5

php_fpm_packages:
  - php5-fpm
  - apache2-mpm-event

apache_fpm_mpm:
  - mpm_event

apache_nonfpm_mpm:
  - mpm_worker
  - mpm_prefork
  - mpm_itk
