---
# defaults file for varnish

VARNISH_CONFIG_PATH: /etc/varnish
VARNISH_LISTEN_PORT: "80"
VARNISH_ADMIN_LISTEN_HOST: "127.0.0.1"
VARNISH_ADMIN_LISTEN_PORT: "6082"
VARNISH_STORAGE: "file,/var/lib/varnish/varnish_storage.bin,256M"

VARNISH_USE_DEFAULT_VCL: true
VARNISH_DEFAULT_BACKEND_HOST: "127.0.0.1"
VARNISH_DEFAULT_BACKEND_PORT: "8080"
VARNISH_SECRET: "14bac2e6-1e34-4770-8078-974373b76c90"